version: '3'
services:
  proxy:
    build: './proxy'
    ports:
      - "3000:3000"
    depends_on: 
      - gateway

  gateway:
    build: './gateway'
    ports:
      - "3001:3000"
    depends_on: 
      - book
      - user

  book:
    build: './book'
    ports:
      - "3002:3000"
    depends_on: 
      - bdb

  user:
    build: './user'
    ports:
      - "3003:3000"
    depends_on: 
      - udb

  udb:
    image: umongo
    ports:
      - "27018:27017"

  bdb:
    image: bmongo
    ports:
      - "27019:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./proxy:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - proxy
